### ISSUE TITLE
Installation failed in StoreFrontUi(Nuxt3/Vue3)

### ISSUE THREAD

**Issue by ateeqTM** [D3T-Distribution/vue3-ssr-carousel#43]
when i install this carousel through this command **yarn add vue3-ssr-carousel** in my Nuxt 3 application getting following errors.
➤ YN0027: vue3-ssr-carousel@unknown can't be resolved to a satisfying range
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/vue3-ssr-carousel

➤ Errors happened when preparing the environment required to run this command.

On this registry URL getting error
https://registry.yarnpkg.com/vue3-ssr-carousel
{
  "error": "Not found"
}

**Comment by quentinmcq** [comment]
Hello,

The installation step in the **README.md** was not correct, you have to use yarn add `@d3t-distribution/vue3-ssr-carousel` instead.
